function [fitresult, min_xx] = fit_polynomial(xx, yy)
%CREATEFIT(XX,YY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xx
%      Y Output: yy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Jul-2014 17:07:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( double(xx), double(yy) );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( ft );
opts.Lower = [-Inf -Inf -Inf];
opts.Upper = [Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


% min = -b / 2a
min_xx = -fitresult.p2/(2*fitresult.p1);
