#!/bin/bash

# Small git hook to automatically create a copy of each .docx file in
# Markdown format so that we can keep track of the changes to Word
# documents.
#
# This script requires pandoc to be installed in the system.

# Author: Ramon Casero <rcasero@gmail.com>
# Version: 0.1.0
# Copyright © 2016 University of Oxford
# 
# University of Oxford means the Chancellor, Masters and Scholars of
# the University of Oxford, having an administrative office at
# Wellington Square, Oxford OX1 2JD, UK. 
#
# This file is part of Gerardus.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details. The offer of this
# program under the terms of the License is subject to the License
# being interpreted in accordance with English Law and subject to any
# action against the University of Oxford being under the jurisdiction
# of the English Courts.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# abort commit if pandoc is not installed
pandoc -v >/dev/null 2>&1 || { 
    echo >&2 "I require pandoc to keep track of changes in .docx files but it's not installed. Aborting."; 
    exit 1; 
}

# go to the top directory of this project, because filenames will be
# referred to that location
cd `git rev-parse --show-toplevel`

# create a Markdown copy of every .docx file that is committed
for file in `git diff --cached --name-only | grep \.docx`
do
    # name of Markdown file
    mdfile="${file%.docx}.md"
    echo Creating Markdown copy of "$file"
    #echo "$mdfile"

    # convert .docx file to Markdown
    pandoc "$file" -o "$mdfile" || {
    	echo "Conversion to Markdown failed";
    	exit 1;
    }

    # add Markdown file to the commit
    echo Adding to the commit "$mdfile"
    git add "$mdfile" || {
    	echo "Git cannot add Markdown file to the commit";
    	exit 1;
    }

done
